### ISSUE TITLE
The url of data can not be reached

### ISSUE THREAD

**Issue by Shun14** [yabufarha/ms-tcn#10]
Hi, thank you for sharing the code.But recently, as the title shows, I can not open the url which leads to download the data.Can you update the url?Thanks.

**Comment by yabufarha** [comment]
Hi,
I've checked the link and it's working!
Kindly note that due to the size of the data, you need to download it using the MEGA desktop app.

**Comment by Shun14** [comment]
> Hi,
> I've checked the link and it's working!
> Kindly note that due to the size of the data, you need to download it using the MEGA desktop app.

OK, thank you very much!
