### ISSUE TITLE
Tool for creating video activity annotations like 50salads

### ISSUE THREAD

**Issue by SbrezVis** [yabufarha/ms-tcn#11]
Hi,
I want to create activity annotations per frame for my own videos,
As I understood in 50salads they gave an annotation for every frame,
Do you know about any good tool I can use in order to create this annotation file?
Something that I mark segments in video, give them annotation and the output will be a file just like the one of 50salads?

**Comment by yabufarha** [comment]
Hi,
Unfortunately I don't have any experience in annotating videos. But there is a new video dataset that is published in CVPR 2019 and the authors make their annotation tool publicly available. Maybe it would be useful for you. Check their project website: https://coin-dataset.github.io/
