### ISSUE TITLE
Video frames to features

### ISSUE THREAD

**Issue by PawelFaron** [yabufarha/ms-tcn#16]
Could you publish your code that converts videos into features?

**Comment by yabufarha** [comment]
Hi,
We extracted features from I3D pre-trained on kinetics using both RGB and flow streams. 
The code to extract frame-wise features is publicly available in this repository: https://github.com/ahsaniqbal/Kinetics-FeatureExtractor

**Comment by GuoxingY** [comment]
Hi,
Did you extract I3D features on Breakfast Dataset after fine-tunning

**Comment by yabufarha** [comment]
Hi @GuoxingY,
The features were extracted without fine-tuning.

**Comment by GuoxingY** [comment]
Got it , thank you so much!
