### ISSUE TITLE
Download GTEA dataset

### ISSUE THREAD

**Issue by GuoxingY** [yabufarha/ms-tcn#18]
Hi,
Could you tell me the url to download the GTEA dataset? I mean, the videos. I can not download the videos from http://ai.stanford.edu/~alireza/GTEA

**Comment by yabufarha** [comment]
Hi,
It seems that the url is not working anymore. Nevertheless, I uploaded the videos and you can download them from here: https://uni-bonn.sciebo.de/s/g2OAlHkgYJgqLIx

**Comment by GuoxingY** [comment]
Thank you for your help!

**Comment by yabufarha** [comment]
No problem :)
