### ISSUE TITLE
Performance on longer videos

### ISSUE THREAD

**Issue by kkirtac** [yabufarha/ms-tcn#21]
Hi @yabufarha ,

I am working with a dataset from another domain (surgical videos), having at least 80 videos and each video is longer than 30 minutes. 

- What was the typical length of videos that you experimented?

- do you think the method can work well with longer videos like 30 minutes or 1 hours? What would be the set of potential parameters to adjust? Could you give suggestions?

**Comment by yabufarha** [comment]
Hi,

The long videos in the datasets I used were around 10 minutes. But there are also a lot of short videos with 2 or 5 minutes. I think the average length on 50Salads is around 6.4 minutes and much shorter on the other datasets.

It would be interesting to see how the model would perform on your dataset. I think you need to adjust the number of layers in the model.
