### ISSUE TITLE
Why masking?

### ISSUE THREAD

**Issue by basavaraj-hampiholi** [yabufarha/ms-tcn#23]
Hello @yabufarha ,

I have read through the paper and did not find information about the mask. But there is usage of mask in the code. Could you please let me know why the masking is used in the code?

Thanks

**Comment by yabufarha** [comment]
Hi @raaj043 ,

The mask is just a technicality to handle batches with videos of different length. 
For more details please check this [thread](https://github.com/yabufarha/ms-tcn/issues/4).

**Comment by raaj043** [comment]
Hi @yabufarha ,

Yes. I got the point. Thank you.
