### ISSUE TITLE
Size of temporal receptive field

### ISSUE THREAD

**Issue by basavaraj-hampiholi** [yabufarha/ms-tcn#26]
Hello,

I see that the temporal receptive field size of single stage is 2047 as you are using only 10(L) layers. Since you are only passing the output probabilities(without additional features) to the next stage, I think the temporal receptive field size does not increase due to multi-stages. 
So, the temporal receptive field size of the entire network is 2047 irrespective of number of stages?

Please clarify my understanding.

Thank you,
Raj

**Comment by yabufarha** [comment]
Dear Raj,

whether you pass probabilities or features, the receptive field increases as you add more stages.

Best,
Yazan

**Comment by raaj043** [comment]
Thanks for clarification Yazan

Best,
Raj
