### ISSUE TITLE
How to get features?

### ISSUE THREAD

**Issue by chenluochuan** [yabufarha/ms-tcn#29]
I am trying to train the network with other dataset. But how can i extract frame-wise features from an example include multiple actions by using I3D network.

**Comment by chenyr0021** [comment]
I meet the same problem. I have the pre-trained i3d model, but the features I extracted on my own are in 1024xT dimension. While the features I download from the website are 2048xT.  I dont know if there is anyway to increase the channels.

**Comment by chenluochuan** [comment]
> I meet the same problem. I have the pre-trained i3d model, but the features I extracted on my own are in 1024xT dimension. While the features I download from the website are 2048xT. I dont know if there is anyway to increase the channels.

Could you please tell me which dataset you used to pre-train i3d model? isolated action dataset or continuous action dataset?

**Comment by yabufarha** [comment]
Hi @chenluochuan, Hi @chenyr0021 

we used I3D pre-trained on Kinetics to extract the features. 
Here is the code we used: https://github.com/ahsaniqbal/Kinetics-FeatureExtractor

@chenyr0021 the 2048 dimensional features are obtained by concatenating two 1024 features vectors from the I3D: one form the RGB stream and the second one from the flow stream.

**Comment by chenyr0021** [comment]
> 
> 
> Hi @chenluochuan, Hi @chenyr0021
> 
> we used I3D pre-trained on Kinetics to extract the features.
> Here is the code we used: https://github.com/ahsaniqbal/Kinetics-FeatureExtractor
> 
> @chenyr0021 the 2048 dimensional features are obtained by concatenating two 1024 features vectors from the I3D: one form the RGB stream and the second one from the flow stream.

I see. Thanks a lot!

**Comment by chenluochuan** [comment]
> Hi @chenluochuan, Hi @chenyr0021
> 
> we used I3D pre-trained on Kinetics to extract the features.
> Here is the code we used: https://github.com/ahsaniqbal/Kinetics-FeatureExtractor
> 
> @chenyr0021 the 2048 dimensional features are obtained by concatenating two 1024 features vectors from the I3D: one form the RGB stream and the second one from the flow stream.

well, thank you very much!
