### ISSUE TITLE
How to fine-tune the results of gtea (FT) ？

### ISSUE THREAD

**Issue by chenwenhe11** [yabufarha/ms-tcn#31]
Thank you very much for your work, I want to know how gtea (FT) got it?

**Comment by yabufarha** [comment]
Hi @chenwenhe11 ,
We fine-tuned the I3D model on training videos from GTEA then use it to extract frame-wise features.
For the features extraction code, please check this repository: https://github.com/ahsaniqbal/Kinetics-FeatureExtractor
