### ISSUE TITLE
Create my own dataset - how to use spatial cnn to create features?

### ISSUE THREAD

**Issue by SbrezVis** [yabufarha/ms-tcn#6]
Hi, 
I would like to try the algorithm you have developed on my own videos, can you elaborate a bit more how do you build such dataset from MP4 files, for example?
1. I'm trying to figure out how to create the features folder, from the paper I understood that is some sort of a transition in spatial cnn, how do I do this for mp4 files for example?
2. How are the ground truth files built, is there a specific tool to create them?
3. What are the files in the split folder? the bundle files?
Thanks

**Comment by yabufarha** [comment]
Hi,
Actually we didn't collect the datasets. These datasets are publicly available datasets that are published by researchers who put an effort to manually annotate the videos and prepare the ground truth files. 

The files in the split folder are the standard way to divide these datasets into training and testing sets as proposed by the researchers who collected the datasets.

Regarding the features, we used a pre-trained two-stream 3d cnn (I3d pre-trained on kinetics). To extract the same features for your own dataset you can use the feature extraction code in https://github.com/ahsaniqbal/Kinetics-FeatureExtractor. You can also use different type of features if you want and then run our model using your features as input.
