### ISSUE TITLE
Qualitative results

### ISSUE THREAD

**Issue by cmhungsteve** [yabufarha/ms-tcn#9]
The visualization for action segmentation you show in the paper (Fig. 3, 4, 6, etc.) are really cool. 
I can generate the frame-level recognition using the code in this repo.
Can you also share the code or script that you use to produce those visualization results?

Thank you so much!

**Comment by yabufarha** [comment]
Unfortunately I don't have a clean script to share. But I'm pretty sure that you will find a lot of examples on the internet.

**Comment by cmhungsteve** [comment]
Thank you.

Do you still have all the raw videos for "50 Salads"?
I am afraid that their official website is dead......

**Comment by yabufarha** [comment]
You can download the videos from this link: https://uni-bonn.sciebo.de/s/EihOV3pEji0MJVa
